default:
  tags:
    - selfhosted-1

# Set to "selfhosted-1" for no-billing 12C/20GB or use "saas-linux-medium-amd64"

variables:

  ANDROID_COMPILE_SDK: "36"

  ANDROID_BUILD_TOOLS: "35.0.0"

stages:
  - building
  - tests
  - release

# Run the build script and create an apk using gradle
buildingJob:
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - when: never
# Run CI when a new tag is created
  interruptible: true
  stage: building
  
  image: fedora:44

  before_script:
  - echo $CI_COMMIT_TAG
  - dnf upgrade -y
  - dnf install -y @development-tools
  - dnf install -y wget glibc-devel.i686 glibc-devel gcc gcc-c++ libstdc++-devel unzip bzip2 cmake make which pkgconf pkg-config 
  # Only needed until JDK 21 isn't used anymore:
  - dnf install -y adoptium-temurin-java-repository && fedora-third-party enable && dnf install -y temurin-21-jdk

  # Set path for ANDROID_home and create directory:
  - export ANDROID_HOME="${PWD}/android-sdk-root"
  - mkdir $ANDROID_HOME

  # Download, unzip, move and add to path the latest android sdk cli tools:
  - wget --no-verbose --output-document=$ANDROID_HOME/cmdline-tools.zip $(curl https://developer.android.com/studio | grep -o "https://dl.google.com/android/repository/commandlinetools-linux-[0-9]*_latest.zip")
  - unzip -q -d "$ANDROID_HOME/cmdline-tools" "$ANDROID_HOME/cmdline-tools.zip"
  - mv -T "$ANDROID_HOME/cmdline-tools/cmdline-tools" "$ANDROID_HOME/cmdline-tools/tools"
  - export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/cmdline-tools/tools/bin

  #Accept all sdk licenses preemptively:
  - yes | sdkmanager --licenses > /dev/null || true

  # Install Android Tooling
  - sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}"
  - sdkmanager "ndk;29.0.14206865"
  - sdkmanager "platform-tools"
  - sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}"

  # Not necessary, just in case someone changed the flag:
  - chmod +x ./gradlew

  script:
    # run twice until i solve the gradle asset issue.
    - ./gradlew assembleDebug -Dorg.gradle.java.home=/usr/lib/jvm/temurin-21-jdk/ &> ./gradle.log
    - ./gradlew assembleDebug -Dorg.gradle.java.home=/usr/lib/jvm/temurin-21-jdk/ &> ./gradle.log
    - cp app/build/outputs/apk/debug/*.apk openmw-android-alpha3-$CI_COMMIT_TAG.apk

  # So we can access the artifacts in the next job:
  after_script:
    - echo "JOB_ID=$CI_JOB_ID" >> job.env
    

  artifacts:
    when: always
    paths:
      - ./buildscript.log
      - ./gradle.log
      - openmw-android-alpha3-$CI_COMMIT_TAG.apk
    expire_in: never
    reports:
      dotenv: job.env


# Create a release with the apk attached, named after the tag which triggered the CI:
releaseJob:
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success
    - when: never
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: buildingJob
      artifacts: true
  script:
    - echo "Create Release $CI_COMMIT_TAG"
    - echo $JOB_ID  
  release:
    name: 'Release $CI_COMMIT_TAG'
    tag_name: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_TAG'
    description: 'Release $CI_COMMIT_TAG'
    assets:
      links:
        - name: "openmw-android-alpha3-$CI_COMMIT_TAG.apk"
          url: "https://gitlab.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/-/jobs/$JOB_ID/artifacts/file/openmw-android-alpha3-$CI_COMMIT_TAG.apk"
